-- AlterTable
ALTER TABLE "public"."SalarySlip" ADD COLUMN     "lateNightHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "overtimeHoursOver60" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "paidLeaveDays" DOUBLE PRECISION NOT NULL DEFAULT 0;
